### PR TITLE
WIPApi/send html tokens via sendtocontact

### PR DESCRIPTION
**Pull request by PurHur**
| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? |N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5933
| BC breaks? | N
| Deprecations? |N 

#### Description:
This PR enables the sendToContact API to send raw html in its tokens. This is often needed for transactional mailings.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Send a html token like this:
```
$params = [
   'tokens' => [
        'strong_name' => 'rawhtml://<b>Strong Man!</b>'
    ],
];
$response = $emailApi->sendToContact($mailId, $contactId, $params);
```

#### List backwards compatibility breaks:
1. Only if someone actually sends "rawhttp://" at the beginning of a token.

### CODE REVIEW

**Comment by marun1980** [comment]
Hi
I downloaded Mautic 3 and checked this feature. It is not working. could you please help me?

**Comment by PurHur** [comment]
Sorry i did not managed to merge all the features of my forks into the trunk on time. Hopefully i am able to do that with 3.1

**Comment by marun1980** [comment]
what should i do to make work this feature with Mautic 3?

**Comment by PurHur** [comment]
Merge it against the new branch

**Comment by benjamin-vauchel** [comment]
I'd love to see this feature in Mautic. Any reason PR hasn't been merged yet ?

**Comment by iparker** [comment]
Are there any news about this? I would be great to have the possibility to use html in tokens.

**Pull request closed without merging**
